### ISSUE TITLE
Link minecraft and discord accounts

### ISSUE THREAD

**Issue by RysingDragon** [NucleusPowered/Phonon#3]
This will make sure users have proper access for things like sending commands/messages from discord.

**Comment by dualspiral** [comment]
What do you think the best way of doing this might be?

**Comment by Mohron** [comment]
Honestly I'd like us to implement OAuth to allow users to authenticate their account with our bot. When a user does this we can create the link between Minecraft & Discord accounts. This way there's no question you control both accounts when the link is made.

**Comment by Time6628** [comment]
We could also use this to sync their in-game rank with a discord rank.

**Comment by dualspiral** [comment]
How would you implement OAuth. I'm aware on the premise of how it works, but where would the endpoint be? Can you do it through Discord?

**Comment by Mohron** [comment]
We would have to have the ability to host the endpoint from the plugin most likely. There's multiple plugins out there with web based interfaces so it wouldn't be completely foreign.

**Comment by dualspiral** [comment]
Hmm. I'd be concerned about security in this case, we'd want to use an HTTPS stack for the endpoint.

**Comment by Mohron** [comment]
Well we would open ourselves up for a lot more possibilities if we authenticate Discord accounts with OAuth2 vs a custom implementation, such as providing a code on on client to be entered on the other. I'm not sure how costly running a HTTPS page would be, but luckily SSL certificates are availible for free (Let's Encrypt).

**Comment by dualspiral** [comment]
I think I'd be concerned about having a full web server potentially built into a plugin - I wonder if we could also provide a way where the HTTPS page could be hosted elsewhere and the plugin sends a token to that server. Adds a layer of complexity though.

Could we thrash out what would need to be done in order for us to get OAuth to work - what's the workflow?

**Comment by Time6628** [comment]
I do not think JDA supports OAuth.

**Comment by Mohron** [comment]
I still feel using OAuth is the most secure way of verifying Discord accounts and will allow us the most flexibility going forward especially when Discord opens up their GameBridge API to the public.

Simpler pairing methods have extra layers of complication due to Direct Message privacy preventing bots from sending or receiving dms from players with it turned on (and bots can't have friends).  

This issue is core to many capabilities our users will want from Phonon so we will need to make it a priority.

**Comment by RysingDragon** [comment]
I agree, OAuth is definitely the best way to go about this. Do you already know how to implement OAuth? If so I'd say to get started whenever you can. I've been looking into it but I still don't think I'd be confident enough on my own right now to be able to fully implement it.

**Comment by Mohron** [comment]
For simplicity and to get this off the ground, what does everyone think about this:
- Add a register command (both sides) that will give you a code to validate yourself on the other side.
- Store linked user as a permissions option ie. `phonon.user`
- Allow group/role equivalents the same way ie. `phonon.role`

**Comment by dualspiral** [comment]
I didn't think about using permission options, that's a good idea.

I think that's reasonable. Because the bot knows who you are trying to link to anyway, you could get it to send a message to the player to run a command on the other platform to confirm within 5 minutes.

**Comment by Mohron** [comment]
What if multiple player try to register at the same time? I was thinking just a 4-6 digit code and no need to tell it who you are since we will know that based on the code.

**Comment by dualspiral** [comment]
You could register and state who you are linking with, so Phonon knows who the source and the target is - but I'm happy either way!
