### ISSUE TITLE
Commands

### ISSUE THREAD

**Issue by dualspiral** [NucleusPowered/Phonon#9]
Unlike Nucleus, where there are loads of commands, I propose that we have one command, `/phonon`, that sub commands can be registered to. Would this be reasonable to others?

What commands do you think we'll need, and what might modules want? I can build a command registration system that is similar to Nucleus' and dynamically register/unregister commands if required.

**Comment by Mohron** [comment]
I for one am for the use of a single command with subcommands. Dynamic registration could be useful due to the module system being in place.
